cluster: yascheduler

codes:
  - Pcrystal

options:
  need_phonons: true
  need_elastic_constants: true
  need_properties: false
  try_oxi_if_fails: true
  resources:
    num_machines: 42
    num_mpiprocs_per_machine: 42

basis_family: MPDSBSL_NEUTRAL

parameters:
  crystal:
    scf:
      k_points: [8, 16]
      dft:
        xc: PBE0
        grid: XLGRID
        numerical:
          TOLLDENS: 8
          TOLLGRID: 16
      numerical:
        TOLDEE: 9
        BIPOSIZE: 64000000
        EXCHSIZE: 64000000
      post_scf: ['PPAN']
    geometry:
      optimise:
        convergence:
          TOLDEE: 9
      phonons:
        ir:
          type: INTCPHF
        raman: true
      elastic_constants:
        type: ELASTCON

  properties:
    band:
      shrink: 8
      k_points: 80
    newk:
      k_points: [6, 6]
    dos:
      n_e: 25000
