cluster: yascheduler

codes:
  - Pcrystal

options:
  need_phonons: true
  need_elastic_constants: true
  need_properties: false
  try_oxi_if_fails: true
  is_magnetic: true
  resources:
    num_machines: 42
    num_mpiprocs_per_machine: 42

basis_family: MPDSBSL_NEUTRAL

parameters:
  crystal:
    scf:
      k_points: [16, 48]
      dft:
        SPIN: True
        xc: PBE0
        grid: XLGRID
        numerical:
          TOLLDENS: 8
          TOLLGRID: 16
      numerical:
        TOLDEE: 9
        BIPOSIZE: 128000000
        EXCHSIZE: 128000000
        TOLINTEG: [8, 8, 8, 8, 30]
        FMIXING: 70
        SMEAR: 0.01
        NOSHIFT: True
      fock_mixing: DIISALLK
      post_scf: ['PPAN']
    geometry:
      optimise:
        hessian: HESSIDEN
        convergence:
          TOLDEE: 9
      phonons:
        TEMPERAT: [35, 5.7125, 1000]
        INTENS:
          INTRAMAN:
            INTCPHF: True
      elastic_constants:
        type: ELASTCON

  properties:
    band:
      shrink: 8
      k_points: 80
    newk:
      k_points: [6, 6]
    dos:
      n_e: 2000
